FROM python:3.12

# Crie um diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie o conteúdo do diretório fastapi para o diretório de trabalho no contêiner (/app)
COPY ./fastapi /app

# Comandos adicionais, como instalação de dependências ou execução de scripts, se necessário

# Comando de entrada para o contêiner (isso pode ser alterado com base nas necessidades do seu projeto)
CMD ["tail", "-f", "/dev/null"]
